### ISSUE TITLE
when use symbols,the rect's position is wrong

### ISSUE THREAD

**Issue by allen3371** [svgdotjs/svg.select.js#31]
Thanks for your plugin,

when i use the symbol ,i got a problem

```
var draw = SVG('drawing').size(300, 300)

var symbol = draw.symbol()
symbol.rect(100, 100).fill('#f09')

var use  = draw.use(symbol).move(100, 100)
use.selectize()

```
the rect's position is wrong

![ccc](https://cloud.githubusercontent.com/assets/28289993/25649092/0b4c3cb2-3005-11e7-8a6d-e638d561df69.png)

**Comment by Fuzzyma** [comment]
Congratulation! It seems like you spotted a bug in Firefox. Bbox for the use element returns x:0, y:0 which is obviously wrong. Chrome does correctly return x:100, y:100 and therefore displays everyting right. However IE is also wrong.

I will report this to mozilla.

**Comment by allen3371** [comment]
Is there any way to solve this problem?temporary

**Comment by Fuzzyma** [comment]
Not in the way its currectly implemented. You could for this repo and add a hack for `<use>` and useragent firefox/IE11 but thats really ugly

**Comment by allen3371** [comment]
thanks a lot!
