### ISSUE TITLE
changing circles with rects 

### ISSUE THREAD

**Issue by ElMaghri** [svgdotjs/svg.select.js#32]
hello
I would like to thank you for the great work 
I would to customize the circles with a small rects.  how can i do this ??

**Comment by Fuzzyma** [comment]
This is only possible by hacking it into the plugin. When you look at line 174-183 you can see that circles gets created. You could easily exchange that with rectangles. Maybe we add an option for that? Or we go for rectangles as default with possibility to round the corners (so people can get circles by full rounding the rect)

**Comment by ElMaghri** [comment]
it's working pretty cool, i think if i charged with image it will working too
