### ISSUE TITLE
import of svg.select.js as ES6 module

### ISSUE THREAD

**Issue by evssraghavendra** [svgdotjs/svg.select.js#33]
While using svg.js in angular2 application, i could import svg.js, but when trying to import svg.select.js the selectize() method is not recognized. 

import * as SVG from 'svg.js'
import 'svg.select.js'

any thoughts what could be wrong or any update on when we can get compatible ES6 modules for all plugins for svg.js

![image](https://user-images.githubusercontent.com/19921843/30579737-7f38760a-9d37-11e7-81cd-b37e70e2f920.png)

**Comment by Fuzzyma** [comment]
until now all plugins rely on teh SVG global to be present. Did you only "test" that in your ide or is this not working in the browser, too? After all selectice is dynamically added to the SVG objects. So a normal IDE would not recognize it even if it is there

**Comment by evssraghavendra** [comment]
![image](https://user-images.githubusercontent.com/19921843/30580926-f20e5e48-9d3b-11e7-9d02-a6458adf06b7.png)

Same is true during run time also.

**Comment by Fuzzyma** [comment]
with `SVG = require('svg.js')` it will most likely work because you put it in the global namespace.
What about `window.SVG = SVG` in your case?

**Comment by saivan** [comment]
I would also add that there should be some documentation about using SVG.js with es6 imports. I'm currently using webpack, and by running:

```import * as SVG from 'svg.js'```

I get no error whilst compiling my code, 
but I do get a mountain of errors once it hits the client 😄

**Comment by jamesjosephrees** [comment]
I was able to build without the error in Angular 5 by adding to the node_modules/svg.js/svg.js.d.ts file. Probably not the most airtight solution as far as preventing errors. But allowed me to build without error in the console.

`selectize(options?:{value:any, options:any}): Element;`

![asolution](https://user-images.githubusercontent.com/32150364/42132156-c41b6ff8-7d55-11e8-91f2-dfc37cbb43bd.jpeg)

**Comment by A-ZC-Lau** [comment]
Also having this problem. It seems like it's not as npm friendly as some of the other plugins (like draggable). Will a more es6 friendly package be released under the `@svgdotjs` name?

**Comment by Fuzzyma** [comment]
This package does not have a svg.js v3 compatible version yet. Therefore it is also not available under the `@svgdotjs` namespace and does not support esm imports

**Comment by adaliszk** [comment]
#63 should resolve this with the types there.

**Comment by adaliszk** [comment]
Long time no ping here, does this still an issue with the merged PR? :)

**Comment by Fuzzyma** [comment]
havent looked into all of this in a long time. I am stuffed with work -.-, will try to sort it out but i cant promise anything

**Comment by Fuzzyma** [comment]
@adaliszk this should be fixed now. In my tests there were no problems with imports
