### ISSUE TITLE
Using selectize() ignores any fill style

### ISSUE THREAD

**Issue by p-adams** [svgdotjs/svg.select.js#34]
I am using version  "svg.select.js": "^2.1.2" in my project. When call selectize on the element, the fill color is ignored and it just renders a black shape.

Here is how i am using it:

    `const draw = svg(this.$refs.shape).size(1000, 1000);
      const rect = draw
      .rect(100, 100)
      .fill("#f06")
      .move(20, 40);

    rect.selectize();`

**Comment by Fuzzyma** [comment]
did you include the css file?

**Comment by p-adams** [comment]
So do I have to require that file? I am not sure how to use it.

**Comment by zibengou** [comment]
@p-adams How did you fix this problem? I encountered the same problem

**Comment by Fuzzyma** [comment]
take a look into the ccss file where the fill is declared. if you dont want that style, change or remove the line from the css file. (ofc you have to include it somehow)
