### ISSUE TITLE
Not an issue but more a request, is it possible to only select left or right

### ISSUE THREAD

**Issue by mchendriks** [svgdotjs/svg.select.js#35]
is it possible to only select left or right and not top, bottom en corners?

**Comment by razvanioan** [comment]
@mchendriks 

I am currently working on a project where I need this behaviour as well (specify exactly which `resize` points to be drawn for a specific element).

Thus, I've implemented the feature myself:

* you can already use [my forked version](https://github.com/razvanioan/svg.select.js)
* maybe [my pull request](https://github.com/svgdotjs/svg.select.js/pull/38) will be merged here too

Enjoy ;)
