### ISSUE TITLE
Doesn't work with latest version

### ISSUE THREAD

**Issue by baloodevil** [svgdotjs/svg.select.js#36]
The following select demo code only works with this older [svg.min.js](http://svgjs.com/svg.select.js/demo/svg.min.js), but not the most recent version of [svg.min.js](https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.min.js).

            var drawing = new SVG('drawing').size('100%', '100%');

            var poly = drawing.polygon('350,50 283,250 450,122 250,122 416,250')
                .attr('pointer-events', "visible");

            poly.on('mousedown', function (e) {
                poly.select().select({
                    deepSelect: true
                });
            }, false);

'''

http://svgjs.com/svg.select.js/demo/svg.min.js

**Comment by Fuzzyma** [comment]
**TL;RD:** use `el.selectize()`

You are right. Thats why the second sentence in the readme is: 
>Note: Duo to naming conflicts the exported method was renamed from select() to selectize().

I had no time for updating the whole readme including the demo page. Iam sorry.

**Comment by baloodevil** [comment]
Thanks for the quick reply!  I tried poly.selectize() also and it says it
is not a function (with the old and newest svg.js).

**Comment by Fuzzyma** [comment]
In that case give me your code where you used it together with the exact version you are trying to use of both svg.js and svg.select.js

**Comment by baloodevil** [comment]
Switch between the two svg.min.js urls.  The first works, the second throws an error.

``` html
<html>
<head>
    <style>
        .svg_select_boundingRect {
            fill: gray;
        }
    </style>
</head>
<body onload="doStuff();">
    <script src="http://svgjs.com/svg.select.js/demo/svg.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.min.js"></script> -->
    <script src="js/svg.select.min.js"></script>
    <script lang="text/javascript">
        function doStuff() {
            var drawing = new SVG('drawing').size('100%', '100%');
            
                    var poly = drawing.polygon('350,50 283,250 450,122 250,122 416,250')
                        .attr('pointer-events', "visible");
            
                    poly.on('mousedown', function (e) {
                        poly.select().select({
                            deepSelect: true
                        });
                    }, false);
        }
    </script>
    <div id="drawing"></div>
</body>
</html>`

**Comment by Fuzzyma** [comment]
Do you use the newest svg.select.js? Because the old does not work with the new svg.js and vice versa.
You take both new versions or both old and it will work (new one with selectize Ofc)

**Comment by Fuzzyma** [comment]
closed due to no reply
