### ISSUE TITLE
Rectangle becomes a black box

### ISSUE THREAD

**Issue by LarsBV** [svgdotjs/svg.select.js#39]
A simple rectangle becomes filled with black as soon as I use selectize. I have attached a jsfiddle 

How comes ?

```
<div id="drawing"></div>
```
```
// initialize SVG.js
var draw = SVG('drawing')

// draw pink square
var rect = draw.rect(100, 100).move(100, 50).fill('#f06')

rect.selectize();
```

http://jsfiddle.net/Lmu56awz/2285/

**Comment by Fuzzyma** [comment]
Include the css file shipped with the libraray and you are good to go
