### ISSUE TITLE
Eval is not the best practice and it may lead to errors

### ISSUE THREAD

**Issue by clusterberries** [svgdotjs/svg.select.js#44]
Hi!

I'm working on Electron application and it uses svg.js and svg.select.js libs. The Electron documentation advises to disable or override eval. So the app has content-security-policy metatag that disables eval. It lead to errors in svg.select.js lib, because it uses eval. 
Do you have any plans to change it? Thanks!

**Comment by Fuzzyma** [comment]
I was about to say that this will not change but then I reviewed the code and I wonder why I didnt see that in the review of the PR. The code can be easily rewritten to: 

```js
this.pointCoord = function (setting, object) {
  return typeof setting !== 'string' ? setting : object[setting]
}
```

feel free to create a PR to fix it :)

**Comment by clusterberries** [comment]
@Fuzzyma the solution will be a bit harder, because there are such expressions as `'width / 2'` that should be evaluated. I already have an idea and I will create a PR

**Comment by Fuzzyma** [comment]
True - jeah ok then there was a reason that was done as it is :D. But when you have a neat idea - go ahead :)
