### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by monsieur42** [svgdotjs/svg.select.js#51]
Hi!

Thanks for this awesome addon!

On this site https://svgjs.com/svg.select.js/ the documentation says:

`var drawing = new SVG('myDrawing').size(500, 500);
drawing.rect(50,50).select()`

but its wrong now it should be:

`var drawing = new SVG('myDrawing').size(500, 500);
drawing.rect(50,50).selectize()`

**Comment by Fuzzyma** [comment]
Yes that is correct. I created this extra site once and never changed it.
I just changed it and hopefully catched all occurrences!

**Comment by monsieur42** [comment]
Super! Thank you!

There is this demo page too:
https://svgjs.com/svg.select.js/demo/index.html

**Comment by Fuzzyma** [comment]
Changed it already :P

**Comment by monsieur42** [comment]
Oh sorry! Than maybe some cache issue. :P

**Comment by Fuzzyma** [comment]
Na, I surely did it at the same time you posted the comment. I remembered it after posting my first answer^^

**Comment by monsieur42** [comment]
Hahha! Alright! :)
