### ISSUE TITLE
this.parent.set is not a function

### ISSUE THREAD

**Issue by notchris** [svgdotjs/svg.select.js#52]
Using the latest version of svg.js and svg.select.js

Following the example, I get `Uncaught TypeError: this.parent.set is not a function`

```
        let draw = SVG('#stage').size(window.innerWidth, window.innerHeight)
        let rect = draw.rect(100, 100).attr({ fill: '#f06' })
        rect.selectize().resize()
```

Thanks!

**Comment by Fuzzyma** [comment]
This plugin wasnt updated for use with svg.js v3 yet. If you need to use it, you need to use a 2.x version of svg.js

**Comment by notchris** [comment]
Thanks! Is the issue that 'set' has changed in v3?

**Comment by Fuzzyma** [comment]
I strongly guess that's only one of the problems here. But yes, set is list now

**Comment by notchris** [comment]
I see. Your suggestion to downgrade worked, and checking the previous documentation also fixed the other issue. Sorry about my confusion. Let me know if I can help with the new version somehow!
