### ISSUE TITLE
Issue with position of elements with transformed parent elements

### ISSUE THREAD

**Issue by KIRA009** [svgdotjs/svg.select.js#69]
https://github.com/svgdotjs/svg.select.js/blob/0291d9d6993ce81ce97dd2210974e293cddd1f90/src/SelectHandler.js#L134

Is there a reason this is used instead of simply
```
const fromShapeToUiMatrix = this.el.node.getCTM();
```

The current version doesn't seem to work if I have an element, whose parent element has transformations on it.

Take the chart on https://www.highcharts.com/demo/highcharts/bar-chart. If you try and select the blue bar beside Africa, the handles appear in the non-transformed position of the element with the current logic. With the suggested logic, the handles appear in the right spot

Below video first shows the outcome with the current code, and the outcome with the suggested code

[screen-capture.webm](https://github.com/user-attachments/assets/c3cb1fe1-afc4-4dbf-9137-3a359f42f3ef)

**Comment by Fuzzyma** [comment]
I looked at the code and there is indeed a bug. We used to put all ui elements into the same parent as the selected element itself. Hence we only needed the transform from element to patent. However, this code was changed and the ui is mounted into the root svg. Hence your code is more correct. Technically we still have to make sure taht the svg itself is not transformed. I will have a look.

Just fyi: it's always better to provide a minimal reproduction case. So no full blown app or video. Just a codepen, fiddle or repo with an example that shows the bug :)

**Comment by KIRA009** [comment]
Thanks for taking a look.

Re: the video, I was actually in the process of creating an svg editor when I noticed the bug. So, it was easier to use the app I already had built for demoing the issue 😅

**Comment by Fuzzyma** [comment]
The bug was easy to spot, so it wasn't a problem. But the video didn't help at all to locate the bug. It just shows "something not working". Better is, to have something I can run immediately. You will make a lot of maintainers happy if you give them a nice reproduction (and they will fix your bugs waaay faster) :D

**Comment by Fuzzyma** [comment]
Published 4.0.2 to fix the problem. I also did a small update to the svg.resize.js bundle because it was bundling svg.select.js instead of importing it
